### ISSUE TITLE
Pattern error in URL regex

### ISSUE THREAD

**Issue by TcM1911** [oasis-open/cti-stix2-json-schemas#100]
The pattern does not compile due to pattern error.
https://github.com/oasis-open/cti-stix2-json-schemas/blob/0f1facfb07d44847e89868e38ed4683fae12d978/schemas/common/url-regex.json#L7

Regex101.com reports `) Unmatched parenthesis` as the issue.

Also the regex is very Python specific so to check against the official schema, the checker needs to use Python's implementation of regex. Would it be possible to use a POSIX regex to allow wider support?

**Comment by clenk** [comment]
I've changed the schema to use the JSON Schema built-in URI format instead. Hopefully this solves the issue for you, but if not please let us know!

**Comment by TcM1911** [comment]
Can you pull in the change to the 2.1 branch so the fix can be used via the URLs in the schema files?
