### ISSUE TITLE
URL regex isn't valid

### ISSUE THREAD

**Issue by dronnix** [oasis-open/cti-stix2-json-schemas#111]
Hi!

URL regex isn't valid: https://github.com/oasis-open/cti-stix2-json-schemas/blob/8e78c35cec59934c23ca08fd69c8793c54abd7b1/schemas/common/url-regex.json#L7

Tested with: 
```
#!/bin/bash
[[ "url.com" =~ ^([a-zA-Z][a-zA-Z0-9+.-]*):(?:\\/\\/((?:(?=((?:[a-zA-Z0-9-._~!$&'()*+,;=:]|%[0-9a-fA-F]{2})*))(\\3)@)?(?=((?:\\[?(?:::[a-fA-F0-9]+(?::[a-fA-F0-9]+)?|(?:[a-fA-F0-9]+:)+(?::[a-fA-F0-9]+)+|(?:[a-fA-F0-9]+:)+(?::|(?:[a-fA-F0-9]+:?)*))\\]?)|(?:[a-zA-Z0-9-._~!$&'()*+,;=]|%[0-9a-fA-F]{2})*))\\5(?::(?=(\\d*))\\6)?)(\\/(?=((?:[a-zA-Z0-9-._~!$&'()*+,;=:@\\/]|%[0-9a-fA-F]{2})*))\\8)?|(\\/?(?!\\/)(?=((?:[a-zA-Z0-9-._~!$&'()*+,;=:@\\/]|%[0-9a-fA-F]{2})*))\\10)?)(?:\\?(?=((?:[a-zA-Z0-9-._~!$&'()*+,;=:@\\/?]|%[0-9a-fA-F]{2})*))\\11)?(?:#(?=((?:[a-zA-Z0-9-._~!$&'()*+,;=:@\\/?]|%[0-9a-fA-F]{2})*))\\12)?$ ]]
```
Possible solution: use URI built-in template: https://json-schema.org/understanding-json-schema/reference/string.html#built-in-formats

Thanks!

**Comment by clenk** [comment]
Hi @dronnix, thanks for the question. My understanding of RFC 3986 is that the scheme portion of a URL is required. This has been discussed in the CTI Technical Committee here: https://github.com/oasis-tcs/cti-stix2/issues/218. Perhaps for the use case of a domain like this example, the `domain-name` object would be appropriate instead of the `url` object in STIX?

**Comment by dronnix** [comment]
@clenk  I'm sorry for the unclear report. Using regex for validating URL is OK in general. But this concrete regex is syntactically incorrect:
```
#!/bin/bash
[[ "https://url.com/path" =~ ^([a-zA-Z][a-zA-Z0-9+.-]*):(?:\\/\\/((?:(?=((?:[a-zA-Z0-9-._~!$&'()*+,;=:]|%[0-9a-fA-F]{2})*))(\\3)@)?(?=((?:\\[?(?:::[a-fA-F0-9]+(?::[a-fA-F0-9]+)?|(?:[a-fA-F0-9]+:)+(?::[a-fA-F0-9]+)+|(?:[a-fA-F0-9]+:)+(?::|(?:[a-fA-F0-9]+:?)*))\\]?)|(?:[a-zA-Z0-9-._~!$&'()*+,;=]|%[0-9a-fA-F]{2})*))\\5(?::(?=(\\d*))\\6)?)(\\/(?=((?:[a-zA-Z0-9-._~!$&'()*+,;=:@\\/]|%[0-9a-fA-F]{2})*))\\8)?|(\\/?(?!\\/)(?=((?:[a-zA-Z0-9-._~!$&'()*+,;=:@\\/]|%[0-9a-fA-F]{2})*))\\10)?)(?:\\?(?=((?:[a-zA-Z0-9-._~!$&'()*+,;=:@\\/?]|%[0-9a-fA-F]{2})*))\\11)?(?:#(?=((?:[a-zA-Z0-9-._~!$&'()*+,;=:@\\/?]|%[0-9a-fA-F]{2})*))\\12)?$ ]]
```
produces: 
```
line 2: unexpected EOF while looking for matching `)'
line 3: unexpected argument to conditional binary operator
line 3: syntax error: unexpected end of file
```
So we need to fix regex, or replace it with [built-in JSON-schema template URI](https://json-schema.org/understanding-json-schema/reference/string.html#built-in-formats)(that matches RFC3986).

**Comment by clenk** [comment]
I've changed the schema to use the URI format like you mentioned. Thanks!
