### ISSUE TITLE
Schema check for timestamp is not aligned with the standard

### ISSUE THREAD

**Issue by TcM1911** [oasis-open/cti-stix2-json-schemas#126]
The schema checks for millisecond precition:
> The timstamp value MUST be precise to the nearest millisecond

https://github.com/oasis-open/cti-stix2-json-schemas/blob/f7c4fbfa2e4430fb44a4a6125ddf3c846e54001e/schemas/common/core.json#L47

While the standard states:

>  The timestamp property MUST be a valid RFC 3339-formatted timestamp [RFC3339] using the format YYYY-MM-DDTHH:mm:ss[.s+]Z where the “s+” represents 1 or more sub-second values. The brackets denote that sub-second precision is optional, and that if no digits are provided, the decimal place MUST NOT be present.

This is causing valid according to the standard timestamp to fail the schema check.

**Comment by clenk** [comment]
Hi @TcM1911, apologies for the delay. You are correct that timestamp properties can have any precision. However, the `created` and `modified` common properties add additional requirements in the STIX 2.1 standard:

> The minimum precision MUST be milliseconds (three digits after the decimal place in seconds), but MAY be more precise.

**Comment by clenk** [comment]
I'm closing this for now, but feel free to reopen if my response doesn't make sense.
