### ISSUE TITLE
The ipfix property is missing a description

### ISSUE THREAD

**Issue by jminnick** [oasis-open/cti-stix2-json-schemas#131]
https://github.com/oasis-open/cti-stix2-json-schemas/blob/56f81906d83fc77b735ac24eec7046970c315ca7/schemas/observables/network-traffic.json#L80

**Comment by clenk** [comment]
Thanks for letting us know! I've added a description, but keep in mind that the full description of the property and all of its requirements can be found in the STIX 2 specification itself.
