### ISSUE TITLE
"not valid under any of the given schemas" when boolean property specified a string

### ISSUE THREAD

**Issue by CyberDaedalus00** [oasis-open/cti-stix2-json-schemas#134]
When a user makes the mistake of specifying a property that takes a boolean value as a string value of "true" or "false", the validation fails with the error "not valid under any of the given schemas" without any clear indication of what is actually wrong.

**Comment by jasonkolodziej** [comment]
!!!!

**Comment by jasonkolodziej** [comment]
There are also some typos with keys `additional*`

**Comment by clenk** [comment]
@CyberDaedalus00 thanks for the feedback, we'll work to improve that message.

@jasonkolodziej Can you please open a separate issue so we can track these typos? Where are the typos, specifically? Thanks!

**Comment by clenk** [comment]
This has been fixed in v2.0.2 of the validator.
