### ISSUE TITLE
Consider use of JCR for the patterns

### ISSUE THREAD

**Issue by athiasjerome** [oasis-open/cti-stix2-json-schemas#21]
Ref.
https://datatracker.ietf.org/doc/draft-newton-json-content-rules/

**Comment by gtback** [comment]
Thanks, @athiasjerome.

Are you talking about using JCR to replace the JSON schemas in this repo, or the STIX Patterning language? If the latter, that would need to be decided by the TC and then could be implemented in this repo. 

If you mean augmenting/replacing JSONSchema, I'm curious what specific features could make JCR an improvement over JSONSchema; I only briefly skimmed the Internet-Draft. I would certainly be  open to it once JCR becomes a published RFC and can be used in Python (for the [cti-stix-validator](https://github.com/oasis-open/cti-stix-validator)). Right now, there are some checks that we can't do in native JSONSchema, and have to have custom Python code for. If JCR is eventually able to represent those, I think it would be a viable alternative, but it just seems too immature for now. 

If I'm wrong or misunderstand what you mean, feel free to re-open this.
