### ISSUE TITLE
Some schemas are invalid against JSON Schema draft 4

### ISSUE THREAD

**Issue by djoodle** [oasis-open/cti-stix2-json-schemas#28]
A couple of the observable schemas fail validation against the latest draft4 schema. The linter returns the following errors:

- observables/process.json
**Field**: .definitions['startup-info-dictionary'].patternProperties['^lpReserved\|lpReserved2$'].type
**Error**: should be equal to one of the allowed values
**Value**: null
**Field**: .definitions['startup-info-dictionary'].patternProperties['^lpReserved\|lpReserved2$'].type
**Error**: should be array
**Value**:  null

- observables/file.json
**Field**: .definitions['file-extensions-dictionary'].patternProperties['^pdf-ext$'].properties['document_info_dict'].patternProperties['description']
**Error**: should be object
**Value**: "Specifies details of the PDF document information dictionary (DID), which includes properties like the document creation data and producer, as a dictionary." 

The second one looks to be a miss-placed bracket, the section _document_info_dict_ should be:

            "document_info_dict": {
              "type:": "object",
              "patternProperties": {
                "^[a-zA-Z0-9_-]{3,256}$": {
                  "type": "string",
                  "description": "Specifies details of the PDF document information dictionary (DID), which includes properties like the document creation data and producer, as a dictionary."
                },
                "pdfid0": {
                  "type": "string",
                  "description": "Specifies the first file identifier found for the PDF file."
                },
                "pdfid1": {
                  "type": "string",
                  "description": "Specifies the second file identifier found for the PDF file."
                }
              }
            }

**Comment by gtback** [comment]
@clenk is going to take a look at this 😀
