### ISSUE TITLE
Reports "Published" is required?

### ISSUE THREAD

**Issue by infosec-alchemist** [oasis-open/cti-stix2-json-schemas#3]
The published field in "reports" appears to be required, as is "created" and "modified".  A report could be created but not yet ready for publishing.  Could this field become optional?

**Comment by gtback** [comment]
Hi @infosec-alchemist, thanks for the feedback. 

The [STIX Specification](https://docs.google.com/document/d/1S5XhY6F5OT599b0OuHtUf8IBzFvNY8RysFHIj93DgsY/edit#heading=h.ha4fpad0r9pf) is what designates this field as required; the schemas in this repo just implement that specification. Any changes to the specification will be reflected in updates to the schemas in this repo.

TC members can comment directly on the mailing list; feedback from non-members should be submitted through the public [comment list](https://www.oasis-open.org/committees/comments/index.php?wg_abbrev=cti).
