### ISSUE TITLE
readme for the examples is out of date. 

### ISSUE THREAD

**Issue by jonathanbaker** [oasis-open/cti-stix2-json-schemas#33]

**Comment by gtback** [comment]
This confused me, until I realized this is about [the README in examples/](https://github.com/oasis-open/cti-stix2-json-schemas/blob/master/examples/README.md), not [the project README](https://github.com/oasis-open/cti-stix2-json-schemas/blob/master/README.md).

**Comment by gtback** [comment]
@ATweedMITRE, can you look at this?

**Comment by ATweedMITRE** [comment]
I have mostly completely rewritten this but it will not be 100% complete until all of the examples have been written/updated. I will update this file further as those are finished.

**Comment by gtback** [comment]
Fixed by #41
