### ISSUE TITLE
multiple relationships with same ID: cti-stix2-json-schemas/examples/campaign-and-threat-actors.json

### ISSUE THREAD

**Issue by deldim1** [oasis-open/cti-stix2-json-schemas#34]
there are multiple relationships with same ID:
relationship--3dcf59c3-30e3-4aa5-9c05-2cbffcee5922

From my knowledge this id should be unique.

**Comment by ATweedMITRE** [comment]
You are right. ID's should be unique here. I generated new ID's for the duplicates, should be good to go now.

**Comment by gtback** [comment]
Fixed by #37
