### ISSUE TITLE
Relationship points to missing object: cti-stix2-json-schemas/examples/indicators-for-C2-with-COA.json

### ISSUE THREAD

**Issue by deldim1** [oasis-open/cti-stix2-json-schemas#35]
Relationship points to missing object:
{
            "type": "relationship",
            "id": "relationship--44298a74-ba52-4f0c-87a3-1824e67d7fad",
            "created_by_ref": "identity--f690c992-8e7d-4b9a-9303-3312616c0220",
            "created": "2016-04-06T20:06:37.000Z",
            "modified": "2016-04-06T20:06:37.000Z",
            "source_ref": "course-of-action--8e2e2d2b-17d4-4cbf-938f-98ee46b3cd3f",
            "target_ref": "malware--31b940d4-6f7f-459a-80ea-9c1f17b5891b",
            "relationship_type": "mitigates"
        },

**Missing Object:** malware--31b940d4-6f7f-459a-80ea-9c1f17b5891b

**Proposed solution:** add the following object to the bundle
{
            "type": "malware",
            "id": "malware--31b940d4-6f7f-459a-80ea-9c1f17b5891b",
            "created_by_ref": "identity--f690c992-8e7d-4b9a-9303-3312616c0220",
            "created": "2016-04-06T20:07:09.000Z",
            "modified": "2016-04-06T20:07:09.000Z",
            "relationship_type": "Poison Ivy"
        }

**Comment by gtback** [comment]
Fixed by #37
