### ISSUE TITLE
Invalid timestamp in APT1 example report

### ISSUE THREAD

**Issue by khho** [oasis-open/cti-stix2-json-schemas#44]
In apt1.json, the first object, "id": "intrusion-set--da1065ce-972c-4605-8755-9cd1074e3b5a", has an invalid timestamp value, "2006-06-00T00:00:00.000000Z", for "first_seen" key. Value for "day" should not be zero.

**Comment by gtback** [comment]
Thanks, @khho. We should definitely fix that example. 

Separately, the timestamp regular expression in the schemas is a bit too loose, which is why this wasn't caught automatically. https://github.com/oasis-open/cti-stix2-json-schemas/blob/master/schemas/common/timestamp.json#L6
