### ISSUE TITLE
Inconsistent IPv4 naming for Pattern field in Indicator 

### ISSUE THREAD

**Issue by khho** [oasis-open/cti-stix2-json-schemas#55]
I see that in the examples for indicator-for-c2-ip-address.json and using-marking-definitions.json, the inidicator patterns for IPv4 is name as  [ipv4addr:value = '10.0.0.0'] instead of [ipv4-addr:value = '10.0.0.0'], with a missing hyphen. The examples documented in STIX 2.0 specification (Part 5 on STIX Patterning) for IPv4 include hyphen. e.g. [ipv4-addr:value = '203.0.113.1' OR ipv4-addr:value = '203.0.113.2'].

**Comment by gtback** [comment]
Thanks, @khho! I'll get these fixed. All of them should use a hyphen.
