### ISSUE TITLE
timestamps are not validated according to RFC 3339

### ISSUE THREAD

**Issue by shpandya** [oasis-open/cti-stix2-json-schemas#62]
Per the STIX2 spec, timestamps are supposed to be RFC 3339 compliant.   RFC 3339 requires at least 1, or more fractional digits after the decimal point, or no decimal point.
This schema is restricting the number of fractional digits to just 3.  RFC 3339 does not have this restriction.  
The validator fails to validate timestamps that have nanosecond precision, which are correct as per RFC 3339.

**Comment by clenk** [comment]
The `created` and `modified` properties are timestamps, but they have the additional requirement of being ["precise to the nearest millisecond (exactly three digits after the decimal place in seconds)."](http://docs.oasis-open.org/cti/stix/v2.0/cs01/part1-stix-core/stix-v2.0-cs01-part1-stix-core.html#_Toc496709274)

These schemas attempt to follow the STIX 2 specification as closely as possible.

**Comment by shpandya** [comment]
OK I missed that additional requirement.  Thanks.
