### ISSUE TITLE
Latest ajv-cli can't resolve refs on schemas using test script command

### ISSUE THREAD

**Issue by thebleucheese** [oasis-open/cti-stix2-json-schemas#67]
Maybe I'm doing something wrong with this, but the latest ajv-cli (and ajv itself) can't resolve refs in the schemas as they are.  This persists even after migrating from draft04 to draft06.  The command in test_examples.sh:
```bash
ajv compile -s "schemas/*/*.json" -r "schemas/*/*.json" --verbose
```
leads to the following results:
```
schema schemas/common/binary.json is valid
schema schemas/common/bundle.json is invalid
error: can't resolve reference identifier.json from id common/bundle.json
...
(many more errors on refs)
```

I've noticed in the python validator you're mutating the schema $refs at runtime so that they can actually resolve by adding "file://" to the front of the relative path.  Is this intended behavior?

**Comment by clenk** [comment]
Hi @thebleucheese, thanks for the report! It looks like some things have changed with draft06 that we'll need to fix (we would welcome a PR!).

However, as a temporary fix until that happens, you can use ajv-cli version 1.1.2 (the last version before draft06 support).

**Comment by thebleucheese** [comment]
Thanks for the response.  I was confused about what was going on so I spoke in a chat with some AJV users about usage, and the author of the library determined there's a bug in one of the latest versions of a dependency.  He created a bug report here:

https://github.com/garycourt/uri-js/issues/31

I think that may resolve the reference resolution issue.  

Additionally, he mentioned that the id's for the JSON schema weren't valid (likely even in the draft04 spec context).  Those ids will serve as a base path and should be absolute URI's.  I'm new to using JSON schema so I'm not confident in making a PR on this since I don't totally grok uri-references and all the other JSON schema particulars.   

Potentially relevant info from the AJV documentation: 
> You don't have to host your schema files at the URIs that you use as schema $id. These URIs are only used to identify the schemas, and according to JSON Schema specification validators should not expect to be able to download the schemas from these URIs.
> The actual location of the schema file in the file system is not used.

So what I did to load them is I do a recursive walk down the schemas dir, loading all the files into plain old js objects.  I manipulated the $id and $ref properties removing all the path information and changed the string contents to just the file name, which works when calling ajv->addSchema(), but my guess is that it still isn't proper, valid JSON schema.  From my limited understanding of the JSON schema spec so far, I think the long term solution is to change the $id params for most of the stix 2 schemas to a real absolute url... something like https://oasis-open.github.io/specs/stix2/schemas/sdos/attack-pattern.json

**Comment by gtback** [comment]
We can also use raw.githubusercontent.com URLs to link to the exact files (even though this isn't strictly required). @clenk what do you think?

**Comment by clenk** [comment]
We had some talk about hosting the schemas in https://github.com/oasis-open/cti-documentation/ but I think using raw.githubusercontent.com URLs would be better as it would remove the need to sync updates between repos.

The `jsonschema` python library we're using in https://github.com/oasis-open/cti-stix-validator doesn't yet have a stable version supporting draft 6, but when it does (soon) we'll update the schemas to draft 6 and fix the IDs.

**Comment by clenk** [comment]
The schemas have now been updated to JSON Schema draft-07, and the $ids and $refs should be fixed now. Please open another issue if the latest changes are still a problem for you. Thanks!
