### ISSUE TITLE
Update schemas to 2.1 WD05

### ISSUE THREAD

**Issue by clenk** [oasis-open/cti-stix2-json-schemas#74]

**Comment by clenk** [comment]
Updated schemas are available here: https://github.com/oasis-open/cti-stix2-json-schemas/tree/update-to-2.1WD03

Tests are failing because the stix2 validator hasn't been updated yet, but when it does we can merge this in.

**Comment by ppatrick-fireeye** [comment]
It appears in the update-to-2.1WD04 that the change to remove the restriction where identifiers MUST be ONLY UUID4 wasn't made yet.

**Comment by zrush-mitre** [comment]
Are all changes from WD03 to current WD implemented? I know that UUID requirements were taken care of in my most recent PR, but is everything fully implemented, or is there leftover pieces from older WD's missing?

**Comment by clenk** [comment]
You are correct; these changes have been made and this can be closed now.
