### ISSUE TITLE
Update schemas to JSON Schema draft 7

### ISSUE THREAD

**Issue by clenk** [oasis-open/cti-stix2-json-schemas#79]

**Comment by johnnemo** [comment]
Hello, I think that this upgrade would solve a lot of issues of v4 schemas are known to have. Are you aware if the validator will work out of the box afterwards? Or it needs extra work to support draft v7?

**Comment by clenk** [comment]
One of the Python dependencies of the validator (`jsonschema`) will need to be updated to a later version that supports draft-07 but other than that I don't anticipate extra work. We will be testing the updates to the STIX schemas and the validator in tandem before making a new release.
