### ISSUE TITLE
Is the bundle ID regenerated for every api call?

### ISSUE THREAD

**Issue by seraphimlord** [oasis-open/cti-stix2-json-schemas#80]
Hi guys, 

Sorry that I have ask here because I could not any ans from stackoverflow or other CS forums.

I understand that Bundle by itself does not have any semantic meaning nor does the bundle-id could be rely on to refer to any objects. Does it mean the bundle-id can be different for every api call even though the user might be getting the same SDOs in the bundle?

**Comment by clenk** [comment]
Hi @seraphimlord, the best place to get answers about STIX is the **cti-users** mailing list: [https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=cti#feedback](https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=cti#feedback)

That said, the bundle's `id` can be different even if it contains the same objects. From the spec: 
> Consuming tools should not rely on the presence of this property or the ability to refer to bundles by ID.
