### ISSUE TITLE
Need to update UUIDv4 regex

### ISSUE THREAD

**Issue by freecodecamp1** [oasis-open/cti-stix2-json-schemas#81]
"pattern": "^[a-z][a-z-]+[a-z]--[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
Need to update above regular expression with below
"pattern": "^[a-z0-9][a-z0-9-]+[a-z0-9]--[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"

path: cti-stix2-json-schemas/schemas/common/identifier.json

**Comment by clenk** [comment]
Hi @freecodecamp1, we've already updated it here: https://github.com/oasis-open/cti-stix2-json-schemas/commit/abe6d2bee255321adbfc272f24efbcd204c88eaf#diff-c8872e93048d8ae44e5b0a4effe33681R8. Sorry for the delay getting back to you.
