### ISSUE TITLE
WD03 Tag

### ISSUE THREAD

**Issue by hanymorcos** [oasis-open/cti-stix2-json-schemas#86]
Hello,

What tag would I use if I want to use a StixValidator  for WD03 STIX 2 specification?

thanks,

Hany

**Comment by clenk** [comment]
Hi @hanymorcos, I'm assuming you mean the 2.1 WD03. You could use the schemas on this branch: [https://github.com/oasis-open/cti-stix2-json-schemas/tree/update-to-2.1WD03](https://github.com/oasis-open/cti-stix2-json-schemas/tree/update-to-2.1WD03) However we're probably going to remove that branch once everything is updated for the 2.1 CSD01.

For the validator you could try this alpha release: [https://pypi.org/project/stix2-validator/2.0.0.dev1/](https://pypi.org/project/stix2-validator/2.0.0.dev1/)

Do you anticipate an ongoing need to support WD03?

**Comment by allink28** [comment]
Hi @clenk ,
Our program is targeting STIX 2.1 WD03 for our public beta with multiple projects involved. So we do anticipate using WD03 for a while.

**Comment by clenk** [comment]
@hanymorcos @allink28 I removed the branch but added the `v2.1-wd03` for your use case.
