### ISSUE TITLE
Various typos

### ISSUE THREAD

**Issue by SavageMessiah** [oasis-open/cti-stix2-json-schemas#92]
https://github.com/oasis-open/cti-stix2-json-schemas/blob/master/schemas/common/core.json#L77 is probably supposed to be "maximum" instead of "maxmimum" 😉

**Comment by SavageMessiah** [comment]
Also https://github.com/oasis-open/cti-stix2-json-schemas/blob/master/schemas/observables/file.json#L208 "type:" has a stray : in it.

If you'd prefer I split these into multiple issues or just open a PR, just yell.

**Comment by clenk** [comment]
Good find, thanks for reporting!
