### ISSUE TITLE
Regular expression for socket-ext.options should allow for multiple word option names

### ISSUE THREAD

**Issue by rpiazza** [oasis-open/cti-stix2-json-schemas#96]
[X] network-traffic--fb055025-dd4f-5fd0-bf8a-c81de67d1eb9: extensions.socket-ext.options: 'IP_MULTICAST_LOOP' does not match any of the regexes: '^(SO|ICMP|ICMP6|IP|IPV6|MCAST|TCP|IRLMP)_[A-Z]*$'

I think the reg_ex should be: ^(SO|ICMP|ICMP6|IP|IPV6|MCAST|TCP|IRLMP)(_[A-Z]+)+$'

**Comment by clenk** [comment]
Fixed by #98.
